name: sync-snippet

on:
  schedule:
    - cron:  '0 0 * * *' # every 24 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1  
    - name: npm ci
      run: npm ci
      working-directory: ./.github/actions/sync-snippet-action
    - name: Sync snippet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNIPPET_ENDPOINT: https://api.staging.fullstory.com/code/v1/snippet?type=esm
      uses: ./.github/actions/sync-snippet-action
