name: FOO

on: push
  #schedule:
  #  - cron:  '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: cd into action directory
      run: cd ./.github/actions/sync-snippet-action
    - name: npm ci
      run: npm ci
    - name: Sync snippet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST: 'test'
      uses: ./.github/actions/sync-snippet-action
